services:
  web:
    image: php:8.3-apache
    container_name: php-apache
    ports:
      - "8081:80"
    volumes:
      - ../src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
